import fs from 'node:fs';
import path from 'node:path';

const OUTPUT_DIR = './src/generated/mcp-server';

async function run() {
  console.log('🚀 Starting Zod-to-MCP Server codegen pipeline...');

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const serverCode = `#!/usr/bin/env node

/**
 * AUTO-GENERATED MCP SERVER
 * Do not edit this file directly.
 * Generated from src/backend/schemas.mjs
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ErrorCode,
  ListToolsRequestSchema,
  McpError,
} from '@modelcontextprotocol/sdk/types.js';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { schemas } from '../../backend/schemas.mjs';

const server = new Server(
  {
    name: 'flight-manual-mcp-server',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Expose all Zod schemas as tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  const tools = [];
  for (const [schemaName, zodSchema] of Object.entries(schemas)) {
    tools.push({
      name: "create_" + schemaName.toLowerCase(),
      description: "Simulate creating a new " + schemaName + " object based on the API schema.",
      inputSchema: zodToJsonSchema(zodSchema),
    });
  }
  return { tools };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const schemaName = Object.keys(schemas).find(
    (name) => request.params.name === "create_" + name.toLowerCase()
  );

  if (!schemaName) {
    throw new McpError(
      ErrorCode.MethodNotFound,
      "Unknown tool: " + request.params.name
    );
  }

  const zodSchema = schemas[schemaName];
  const parsed = zodSchema.safeParse(request.params.arguments);

  if (!parsed.success) {
    throw new McpError(
      ErrorCode.InvalidParams,
      "Invalid " + schemaName + " payload: " + parsed.error.message
    );
  }

  return {
    content: [
      {
        type: 'text',
        text: "Successfully validated and 'created' " + schemaName + ":\\n" + JSON.stringify(parsed.data, null, 2),
      },
    ],
  };
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('Flight Manual MCP server running on stdio');
}

main().catch((error) => {
  console.error('Server error:', error);
  process.exit(1);
});
`;

  const targetPath = path.join(OUTPUT_DIR, 'server.mjs');
  fs.writeFileSync(targetPath, serverCode);
  fs.chmodSync(targetPath, 0o755); // Make executable

  console.log("✅ Projected MCP Server to " + targetPath);
  console.log('\\n✨ MCP Server codegen complete. You can run it with:');
  console.log("  node " + targetPath);
}

run();
